services: 

  backend-shell: 
    container_name: backend-shell 
    build: ./backend 
    entrypoint: bash -c 
    profiles: ["backend"]

  backend: 
    container_name: backend 
    build: ./backend 
    profiles: ["backend"]
    ports: 
    - "5000:5000"
    networks: 
      - bias-network
    environment: 
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
      - AWS_DEFAULT_REGION=us-east-2
    volumes: 
      - .:/code
      - C:\Users\trevo\.aws\credentials:/app/.aws/credentials:ro
  
  data-collection:
    container_name: data-collection
    build: ./data_collection
    profiles: ["data"]
    ports: 
      - "5002:5000"
    depends_on: 
      - selenium
  
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    profiles: ["data"]
    ports: 
    - "4444:4444"
    logging:
      driver: none
  
  sandbox:
    container_name: sandbox
    build: ./sandbox
    profiles: ["sandbox"]

networks: 
  bias-network:
    name: bias-network 