services: 

  backend_shell: 
    container_name: backend_shell 
    build: ./backend 
    entrypoint: bash -c 
    profiles: ["backend"]

  backend: 
    container_name: backend 
    build: ./backend 
    profiles: ["backend"]
    ports: 
    - "5000:5000"

  dynamo_db: 
    container_name: dynamo_db
    image: localstack/localstack
    environment: 
      - SERVICES=dynamo_db
      - DEFAULT_REGION=us-east-1
    ports: 
      - "5010:4566"
