services: 

  backend_shell: 
    container_name: backend_shell 
    build: ./backend 
    entrypoint: bash -c 
    profiles: ["backend"]

  backend: 
    container_name: backend 
    build: ./backend 
    profiles: ["backend"]
    ports: 
    - "5000:5000"